version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "${PORT:-5001}:5001"
    environment:
      - PORT=${PORT:-5001}
      - JWT_SECRET=${JWT_SECRET:-yoursecretkey}
    command: node server.js # Start the backend server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  backend_data: # Volume to persist SQLite database

